### ISSUE TITLE
lack of pinned package versions in requirements.txt results in all tests failing

### ISSUE THREAD

**Issue by wetjenk** [drmonkeysee/ecs-scheduler#1]
lack of pinned package versions in requirements.txt results in all tests failing

example:

```
======================================================================
ERROR: test.webapi.test_subpackage (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.webapi.test_subpackage
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/ubuntu/000_github_repos/ecs-scheduler-1.0.1/test/webapi/test_subpackage.py", line 5, in <module>
    import ecs_scheduler.webapi.home
  File "/home/ubuntu/000_github_repos/ecs-scheduler-1.0.1/ecs_scheduler/webapi/__init__.py", line 8, in <module>
    from .home import Home
  File "/home/ubuntu/000_github_repos/ecs-scheduler-1.0.1/ecs_scheduler/webapi/home.py", line 5, in <module>
    from .jobs import Jobs
  File "/home/ubuntu/000_github_repos/ecs-scheduler-1.0.1/ecs_scheduler/webapi/jobs.py", line 9, in <module>
    from ..datacontext import JobAlreadyExists, JobNotFound, InvalidJobData
  File "/home/ubuntu/000_github_repos/ecs-scheduler-1.0.1/ecs_scheduler/datacontext.py", line 16, in <module>
    from .serialization import JobSchema, JobCreateSchema
  File "/home/ubuntu/000_github_repos/ecs-scheduler-1.0.1/ecs_scheduler/serialization.py", line 67, in <module>
    class JobSchema(marshmallow.Schema):
  File "/home/ubuntu/000_github_repos/ecs-scheduler-1.0.1/ecs_scheduler/serialization.py", line 80, in JobSchema
    scheduleStart = marshmallow.fields.LocalDateTime()
AttributeError: module 'marshmallow.fields' has no attribute 'LocalDateTime'


----------------------------------------------------------------------
Ran 126 tests in 0.300s

FAILED (errors=32)
make: *** [Makefile:28: check] Error 1
```

this code looks pretty awesome. :) fixing this would probably reduce friction in user uptake

**Comment by drmonkeysee** [comment]
I'll take a look this weekend, I can probably get it working with latest versions and then freeze everything there. That said, this was originally written in 2015 when AWS ECS had very few features and we needed a container scheduler. These days I'm pretty sure you can do everything ecs-scheduler does using native ECS tooling 🤷‍♀️

**Comment by drmonkeysee** [comment]
I believe this is fixed. All dependencies are now pinned, all tests pass, and running `debug` or building and running the provided Docker image all work.

**Comment by wetjenk** [comment]
hi, that's great news! yeah - i guess you could do a lot of in ecs, but i'm just interested in some of the learning parts of coding something based on apscheduler.

Could you let me know once you have merged the changes pls? :)

**Comment by drmonkeysee** [comment]
Done
