### ISSUE TITLE
boto3 need region set

### ISSUE THREAD

**Issue by wetjenk** [drmonkeysee/ecs-scheduler#3]
FYI:
get this error
````
*** Stats server enabled on /tmp/ecss-stats.sock fd: 11 ***
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/uwsgidecorators.py", line 73, in postfork_chain_hook
    f()
  File "/usr/lib/python3.9/site-packages/uwsgidecorators.py", line 94, in __call__
    return self.f()
  File "/opt/ecs-scheduler/./ecs_scheduler/app.py", line 48, in _setup_application
    _launch_scheduld(ops_queue, jobs_dc)
  File "/opt/ecs-scheduler/./ecs_scheduler/app.py", line 55, in _launch_scheduld
    scheduler = scheduld.create(ops_queue, jobs_dc)
  File "/opt/ecs-scheduler/./ecs_scheduler/scheduld/__init__.py", line 14, in create
    job_exec = JobExecutor()
  File "/opt/ecs-scheduler/./ecs_scheduler/scheduld/execution.py", line 36, in __init__
    self._ecs = boto3.client('ecs')
  File "/usr/lib/python3.9/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/usr/lib/python3.9/site-packages/botocore/session.py", line 847, in create_client
    client = client_creator.create_client(
  File "/usr/lib/python3.9/site-packages/botocore/client.py", line 86, in create_client
    client_args = self._get_client_args(
  File "/usr/lib/python3.9/site-packages/botocore/client.py", line 355, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/lib/python3.9/site-packages/botocore/args.py", line 71, in get_client_args
    final_args = self.compute_client_args(
  File "/usr/lib/python3.9/site-packages/botocore/args.py", line 148, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/usr/lib/python3.9/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/lib/python3.9/site-packages/botocore/args.py", line 302, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/usr/lib/python3.9/site-packages/botocore/client.py", line 430, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/usr/lib/python3.9/site-packages/botocore/regions.py", line 133, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/usr/lib/python3.9/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

resolved by:
https://stackoverflow.com/questions/40377662/boto3-client-noregionerror-you-must-specify-a-region-error-only-sometimes

i'm good on my side - just letting you knows

**Comment by drmonkeysee** [comment]
yeah i considered it outside the scope of the documentation to describe how to talk to AWS programmatically, other than a brief mention in the README.md:

> To learn how to pass your AWS credentials to an application using boto3 consult the boto3 docs (link to docs here)

their documentation describes credential management in far better detail and i figured the actual productization of ecs-scheduler in one's infrastructure will be dictated by their own organization's DevOps practices; i didn't see much point in favoring any particular approach in the docs. i can probably make it clearer that the ecs-scheduler does make certain assumptions when creating the boto3 clients (i.e. it expects them to be found via the environment rather than passed as an argument at the call sites).

the upshot is do whatever you want in order to make Boto3 happy. for my own personal dev testing i'd always pass my credentials into the container via `--env-file` (which gets a brief mention in the sample code) but there's a dozen different ways you can manage AWS creds.

**Comment by wetjenk** [comment]
no worries. but just to clarify, i'm not sure whether it picks the region up. the error is on the region, not the creds. i edited the code to explicitly add the region

e.g. in triggers.py
```
self._sqs = boto3.resource('sqs',  region_name='eu-west-1')
```

**Comment by drmonkeysee** [comment]
It will pick it up if you define default region, either within the container environment or embedding a config file within the container itself, e.g. https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables (`AWS_DEFAULT_REGION=eu-west-1`)

That's not super-clear from the documentation though, I'll update it.

**Comment by wetjenk** [comment]
Gotcha! many thanks :)
